lastupdatecheck: 0
recentrepos:
    - /home/yvesd/Nixos
    - /home/yvesd/Codingspaces/AcademAmigo
startuppopupversion: 5
lastversion: 0.42.0
customcommandshistory:
    - q
hidecommandlog: false
ignorewhitespaceindiffview: true
diffcontextsize: 3
localbranchsortorder: recency
remotebranchsortorder: alphabetical
gitlogorder: topo-order
gitlogshowgraph: always
