{
  lib,
  pkgs,
  pkgs-unstable,
  desktopWindowManager,
  ...
}: let
  mangowcPatched = pkgs-unstable.callPackage ../../packages/mango-patched.nix {};
  shell = "${pkgs.bash}/bin/sh";
  wlrRandr = lib.getExe pkgs.wlr-randr;
  laptopOutput = "eDP-1";
  laptopMode = "2560x1600@165.002Hz";
  laptopPosition = "3440,0";
  laptopScale = "1.333333";
  enableLaptopPanel = "${wlrRandr} --output ${laptopOutput} --on --mode ${laptopMode} --pos ${laptopPosition} --scale ${laptopScale}";
  restoreMonitors = "${wlrRandr} --output DP-2 --mode 3440x1440@143.975Hz --pos 0,0 --scale 1 --output ${laptopOutput} --on --mode ${laptopMode} --pos ${laptopPosition} --scale ${laptopScale}";
  applyLidState = "/home/yvesd/.config/mango/apply-lid-state.sh";
  autostartScript = "/home/yvesd/.config/mango/autostart.sh";
  lidSwitchWatcher = "/home/yvesd/.config/mango/lid-switch-watch.sh";
  mmsg = "${mangowcPatched}/bin/mmsg";
  qs = "/run/current-system/sw/bin/qs";
  chatgptScratchpad = "/home/yvesd/nixos/homeManager/modules/scripts/toggle-chatgpt-scratchpad.sh";
  sleep = "${pkgs.coreutils}/bin/sleep";
  runtimePath = lib.makeBinPath [pkgs.bash pkgs.coreutils mangowcPatched pkgs.wlr-randr];
  mangoScrollerMinProportion = "0.333333";
  mangoCycleLayouts = [
    "scroller"
    "tile"
    "center_tile"
    "grid"
  ];
  mangoSupportedLayouts = [
    "scroller"
    "tile"
    "grid"
    "monocle"
    "deck"
    "center_tile"
    "right_tile"
    "vertical_scroller"
    "vertical_tile"
    "vertical_grid"
    "vertical_deck"
    "dwindle"
    "fair"
    "vertical_fair"
  ];
  # ALL built-in layouts in mango's layouts[] array order — mmsg reports the
  # current layout as a 0-based index into this array, and the Super+Shift+Tab
  # cycle-all script maps through it. Keep in sync with src/layout/layout.h
  # when bumping mango.
  mangoAllLayouts = [
    "tile"
    "scroller"
    "grid"
    "monocle"
    "deck"
    "center_tile"
    "right_tile"
    "vertical_scroller"
    "vertical_tile"
    "vertical_grid"
    "vertical_deck"
    "dwindle"
    "fair"
    "vertical_fair"
  ];
  cycleAllLayouts = "/home/yvesd/.config/mango/cycle-all-layouts.sh";
  unsupportedMangoCycleLayouts = lib.filter (layout: !(builtins.elem layout mangoSupportedLayouts)) mangoCycleLayouts;
  mangoCycleLayoutConfig = lib.concatStringsSep "," mangoCycleLayouts;

  mangoConfig = ''
    # Generated by /home/yvesd/nixos/homeManager/modules/mango.nix

    # Window effects
    blur=0
    blur_layer=0
    blur_optimized=1
    shadows=0
    layer_shadows=0
    shadow_only_floating=1
    border_radius=0
    no_radius_when_single=1
    focused_opacity=1.0
    unfocused_opacity=1.0

    # Animation
    animations=0
    layer_animations=0

    # Scroller layout
    scroller_structs=20
    scroller_default_proportion=${mangoScrollerMinProportion}
    scroller_focus_center=0
    scroller_prefer_center=0
    edge_scroller_pointer_focus=1
    scroller_default_proportion_single=1.0
    scroller_proportion_preset=${mangoScrollerMinProportion},0.5,1.0

    # Layouts cycled by Super+Tab. Edit mangoCycleLayouts in this Nix module.
    circle_layout=${mangoCycleLayoutConfig}

    # Zero gaps for every Mango layout, including overview.
    smartgaps=0
    overviewgappi=0
    overviewgappo=0
    gappih=0
    gappiv=0
    gappoh=0
    gappov=0

    # Misc
    no_border_when_single=0
    focus_on_activate=1
    idleinhibit_ignore_visible=0
    sloppyfocus=1
    warpcursor=1
    focus_cross_monitor=0
    focus_cross_tag=0
    exchange_cross_monitor=0
    scratchpad_cross_monitor=1
    enable_floating_snap=0
    snap_distance=30
    cursor_size=24
    drag_tile_to_tile=1

    # Keyboard and pointer
    repeat_rate=25
    repeat_delay=600
    numlockon=0
    xkb_rules_layout=us
    disable_trackpad=0
    tap_to_click=1
    tap_and_drag=1
    drag_lock=1
    trackpad_natural_scrolling=0
    disable_while_typing=1
    mouse_natural_scrolling=0

    # Appearance
    scratchpad_width_ratio=0.8
    scratchpad_height_ratio=0.9
    borderpx=2
    rootcolor=0x222436ff
    bordercolor=0x00000000
    focuscolor=0x7aa2f7ee
    maximizescreencolor=0x89aa61ff
    urgentcolor=0xff757fff
    scratchpadcolor=0x3d59a1ff
    globalcolor=0xbb9af7ee
    overlaycolor=0x14a57cff

    # Monitor layout mirrors homeManager/modules/hyprland/monitors.nix.
    # mango 0.14 key:value format; layout now comes from the tagrules below.
    monitorrule=name:DP-2,scale:1,x:0,y:0,width:3440,height:1440,refresh:174.963
    monitorrule=name:eDP-1,scale:1.333333,x:3440,y:0,width:2560,height:1600,refresh:165.002

    # mango 0.14 no longer runs ~/.config/mango/autostart.sh by convention;
    # exec-once replaces it (starts quickshell + user services).
    exec-once=${autostartScript}

    # Closing disables the laptop panel; opening reenables it. A user service
    # also watches the ACPI lid state because Mango switch events can be
    # unreliable on this host.
    switchbind=fold,spawn,${applyLidState} closed
    switchbind=unfold,spawn,${applyLidState} open

    # Tags use Mango's scroller layout to approximate the current Hyprland scrolling layout.
    tagrule=id:1,layout_name:scroller
    tagrule=id:2,layout_name:scroller
    tagrule=id:3,layout_name:scroller
    tagrule=id:4,layout_name:scroller
    tagrule=id:5,layout_name:scroller
    tagrule=id:6,layout_name:scroller
    tagrule=id:7,layout_name:scroller
    tagrule=id:8,layout_name:scroller
    tagrule=id:9,layout_name:scroller
    tagrule=id:10,layout_name:scroller

    # Quickshell command palette: keep Super+A like Hyprland, but let Mango center it as a floating window.
    windowrule=title:Command Palette,isfloating:1,isnoborder:1,isoverlay:1,noswallow:1,width:720,height:560
    windowrule=appid:zen-beta,title:^ChatGPT,isfloating:1,isnamedscratchpad:1,noswallow:1,width:1400,height:1100

    # Core bindings
    bind=SUPER,r,reload_config
    bind=SUPER,comma,spawn,${qs} ipc call hints toggle
    bind=SUPER,g,spawn,bash /home/yvesd/nixos/homeManager/modules/scripts/lights.bash
    bind=SUPER+SHIFT,g,spawn,${qs} ipc call lights toggle
    bind=SUPER,t,spawn,ghostty -e herdr
    bind=SUPER,q,killclient,
    bind=SUPER,e,spawn,ghostty -e yazi
    bind=SUPER,w,togglefloating,
    bind=SUPER,a,spawn,${qs} ipc call command-palette toggle

    # Browser and app bindings
    bind=SUPER,f,spawn,zen-scoped
    bind=SUPER,h,spawn_shell,zen-scoped --private-window; ${qs} ipc call hints visable 0
    bind=SUPER,y,spawn,zen-scoped --new-window https://www.youtube.com/feed/subscriptions
    bind=SUPER,u,spawn,zen-scoped --new-window https://slate.sheridancollege.ca/d2l/login
    bind=SUPER+SHIFT,d,spawn,linuxmis
    bind=SUPER,d,spawn,linuxmis stream yves desktop

    # Shell companion actions
    bind=SUPER,b,spawn,${chatgptScratchpad}
    bind=SUPER,c,spawn,${qs} ipc call zellij-sessions toggle
    bind=SUPER,l,spawn,${qs} ipc call lock locked true
    bind=SUPER,p,spawn_shell,grim -t png -g "$(slurp -d)" - | wl-copy -t image/png

    # Scroller layout approximations
    bind=SUPER,Tab,switch_layout
    bind=SUPER+SHIFT,Tab,spawn,${cycleAllLayouts}
    bind=SUPER,period,exchange_client,left
    bind=SUPER,slash,exchange_client,right

    # Navigation
    bind=SUPER,Left,focusdir,left
    bind=SUPER,Right,focusdir,right
    bind=SUPER,Up,focusdir,up
    bind=SUPER,Down,focusdir,down
    bind=SUPER+ALT,Left,focusdir,left
    bind=SUPER+ALT,Right,focusdir,right
    bind=SUPER+ALT,Up,focusdir,up
    bind=SUPER+ALT,Down,focusdir,down

    # Resize
    bind=SUPER+SHIFT,Right,resizewin,+30,+0
    bind=SUPER+SHIFT,Left,resizewin,-30,+0
    bind=SUPER+SHIFT,Up,resizewin,+0,-30
    bind=SUPER+SHIFT,Down,resizewin,+0,+30

    # Tags mapped from Hyprland workspaces
    bind=SUPER,1,view,1,0
    bind=SUPER,2,view,2,0
    bind=SUPER,3,view,3,0
    bind=SUPER,4,view,4,0
    bind=SUPER,5,view,5,0
    bind=SUPER,6,view,6,0
    bind=SUPER,7,view,7,0
    bind=SUPER,8,view,8,0
    bind=SUPER,9,view,9,0
    bind=SUPER,0,view,10,0

    bind=SUPER+SHIFT,1,tag,1,0
    bind=SUPER+SHIFT,2,tag,2,0
    bind=SUPER+SHIFT,3,tag,3,0
    bind=SUPER+SHIFT,4,tag,4,0
    bind=SUPER+SHIFT,5,tag,5,0
    bind=SUPER+SHIFT,6,tag,6,0
    bind=SUPER+SHIFT,7,tag,7,0
    bind=SUPER+SHIFT,8,tag,8,0
    bind=SUPER+SHIFT,9,tag,9,0
    bind=SUPER+SHIFT,0,tag,10,0

    # Mouse bindings
    mousebind=SUPER,btn_left,moveresize,curmove
    mousebind=SUPER,btn_right,moveresize,curresize

    # Layer rules
    layerrule=animation_type_open:zoom,layer_name:rofi
    layerrule=animation_type_close:zoom,layer_name:rofi
  '';
in
  lib.mkIf (desktopWindowManager == "mango") {
    assertions = [
      {
        assertion = mangoCycleLayouts != [];
        message = "Mango cycle layouts must contain at least one layout.";
      }
      {
        assertion = unsupportedMangoCycleLayouts == [];
        message = "Mango cycle layouts contain unsupported layout names: ${lib.concatStringsSep ", " unsupportedMangoCycleLayouts}. Supported layouts: ${lib.concatStringsSep ", " mangoSupportedLayouts}.";
      }
    ];

    xdg.configFile."mango/config.conf".text = mangoConfig;

    xdg.configFile."mango/restore-monitors.sh" = {
      executable = true;
      text = ''
        #!${shell}
        set -eu

        export XDG_RUNTIME_DIR="''${XDG_RUNTIME_DIR:-/run/user/$(${pkgs.coreutils}/bin/id -u)}"
        export WAYLAND_DISPLAY="''${WAYLAND_DISPLAY:-wayland-0}"

        ${restoreMonitors}
      '';
    };

    xdg.configFile."mango/cycle-all-layouts.sh" = {
      executable = true;
      text = ''
        #!${shell}
        set -eu

        # Super+Shift+Tab: cycle through ALL built-in layouts (Super+Tab's
        # switch_layout only cycles the curated circle_layout list). mmsg
        # reports layout_index as a 0-based index into mango's layouts[]
        # array; mangoAllLayouts mirrors that order.
        layouts="${lib.concatStringsSep " " mangoAllLayouts}"
        count=${toString (builtins.length mangoAllLayouts)}

        state="$(${mmsg} get all-monitors)"
        seg="$(printf '%s' "$state" | ${pkgs.coreutils}/bin/tr "{" "\n" | ${pkgs.gnugrep}/bin/grep "\"active\":true" | ${pkgs.coreutils}/bin/head -n 1)"
        idx="$(printf '%s' "$seg" | ${pkgs.gnugrep}/bin/grep -oE "\"layout_index\":[0-9]+" | ${pkgs.coreutils}/bin/head -n 1 | ${pkgs.coreutils}/bin/cut -d: -f2)"

        if [ -z "$idx" ]; then
          exit 1
        fi

        next=$(((idx + 1) % count))
        i=0
        for name in $layouts; do
          if [ "$i" -eq "$next" ]; then
            exec ${mmsg} dispatch "setlayout,$name"
          fi
          i=$((i + 1))
        done
      '';
    };

    xdg.configFile."mango/apply-lid-state.sh" = {
      executable = true;
      text = ''
        #!${shell}
        set -eu

        export XDG_RUNTIME_DIR="''${XDG_RUNTIME_DIR:-/run/user/$(${pkgs.coreutils}/bin/id -u)}"
        export WAYLAND_DISPLAY="''${WAYLAND_DISPLAY:-wayland-0}"

        state="''${1:-}"

        case "$state" in
          closed)
            ${wlrRandr} --output ${laptopOutput} --off || ${mmsg} dispatch disable_monitor,${laptopOutput} || true
            ;;
          open)
            ${enableLaptopPanel} || ${mmsg} dispatch enable_monitor,${laptopOutput} || true
            ;;
          *)
            printf 'usage: %s open|closed\n' "$0" >&2
            exit 2
            ;;
        esac
      '';
    };

    xdg.configFile."mango/lid-switch-watch.sh" = {
      executable = true;
      text = ''
        #!${shell}
        set -eu

        lid_state_path="''${LID_STATE_PATH:-}"

        if [ -z "$lid_state_path" ]; then
          for candidate in /proc/acpi/button/lid/*/state; do
            if [ -r "$candidate" ]; then
              lid_state_path="$candidate"
              break
            fi
          done
        fi

        if [ -z "$lid_state_path" ] || [ ! -r "$lid_state_path" ]; then
          printf 'No readable ACPI lid state file found\n' >&2
          exit 0
        fi

        read_lid_state() {
          IFS= read -r line <"$lid_state_path" || {
            printf 'unknown\n'
            return
          }

          case "$line" in
            *closed*) printf 'closed\n' ;;
            *open*) printf 'open\n' ;;
            *) printf 'unknown\n' ;;
          esac
        }

        last_state="$(read_lid_state)"

        if [ "$last_state" = "closed" ]; then
          ${applyLidState} closed
        fi

        while :; do
          state="$(read_lid_state)"

          if [ "$state" != "$last_state" ]; then
            case "$state" in
              open | closed)
                ${applyLidState} "$state"
                ;;
            esac

            last_state="$state"
          fi

          ${sleep} 1
        done
      '';
    };

    xdg.configFile."mango/autostart.sh" = {
      executable = true;
      text = ''
        #!${shell}
        set -eu

        export XDG_CURRENT_DESKTOP="''${XDG_CURRENT_DESKTOP:-mango}"
        export XDG_SESSION_DESKTOP="''${XDG_SESSION_DESKTOP:-mango}"
        export XDG_SESSION_TYPE="''${XDG_SESSION_TYPE:-wayland}"
        export WAYLAND_DISPLAY="''${WAYLAND_DISPLAY:-wayland-0}"
        export QT_QPA_PLATFORM="''${QT_QPA_PLATFORM:-wayland}"

        systemctl --user import-environment DISPLAY QT_QPA_PLATFORM WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP XDG_SESSION_TYPE
        if command -v dbus-update-activation-environment >/dev/null 2>&1; then
          dbus-update-activation-environment --systemd DISPLAY QT_QPA_PLATFORM WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP XDG_SESSION_TYPE
        fi

        systemctl --user start quickshell.service quickshell-notification-server.service mango-lid-switch.service
      '';
    };

    systemd.user.services.mango-lid-switch = {
      Unit = {
        Description = "Mango lid switch monitor handler";
        After = ["graphical-session.target"];
        PartOf = ["graphical-session.target"];
      };

      Service = {
        ExecStart = "${shell} ${lidSwitchWatcher}";
        # on-failure: the watcher exits 0 when no ACPI lid file exists; "always"
        # would crash-loop it into the start limit on such hosts.
        Restart = "on-failure";
        RestartSec = 2;
        Environment = [
          "PATH=${runtimePath}"
          "XDG_CURRENT_DESKTOP=mango"
          "XDG_SESSION_DESKTOP=mango"
          "XDG_SESSION_TYPE=wayland"
          "WAYLAND_DISPLAY=wayland-0"
        ];
      };

      Install = {
        WantedBy = ["graphical-session.target"];
      };
    };
  }
